language: node_js
node_js:
  - "5"
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - 'node_modules/protractor/bin/webdriver-manager update --standalone --firefox'
  - 'node_modules/protractor/bin/webdriver-manager start 2>&1 &'
  - sleep 3
after_success:
    "gulp deploy --ip $FTP_IP --user $FTP_USER --password $FTP_PASSWORD"
